
package cranendc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.iata.iata._2015._00._2020_1.iata_airlineprofilerq.IATAAirlineProfileRQ;
import org.iata.iata._2015._00._2020_1.iata_airlineprofilers.IATAAirlineProfileRS;
import org.iata.iata._2015._00._2020_1.iata_airshoppingrq.IATAAirShoppingRQ;
import org.iata.iata._2015._00._2020_1.iata_airshoppingrs.IATAAirShoppingRS;
import org.iata.iata._2015._00._2020_1.iata_offerpricerq.IATAOfferPriceRQ;
import org.iata.iata._2015._00._2020_1.iata_offerpricers.IATAOfferPriceRS;
import org.iata.iata._2015._00._2020_1.iata_orderchangerq.IATAOrderChangeRQ;
import org.iata.iata._2015._00._2020_1.iata_ordercreaterq.IATAOrderCreateRQ;
import org.iata.iata._2015._00._2020_1.iata_orderreshoprq.IATAOrderReshopRQ;
import org.iata.iata._2015._00._2020_1.iata_orderreshoprs.IATAOrderReshopRS;
import org.iata.iata._2015._00._2020_1.iata_orderretrieverq.IATAOrderRetrieveRQ;
import org.iata.iata._2015._00._2020_1.iata_orderrulesrq.IATAOrderRulesRQ;
import org.iata.iata._2015._00._2020_1.iata_orderrulesrs.IATAOrderRulesRS;
import org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS;
import org.iata.iata._2015._00._2020_1.iata_seatavailabilityrq.IATASeatAvailabilityRQ;
import org.iata.iata._2015._00._2020_1.iata_seatavailabilityrs.IATASeatAvailabilityRS;
import org.iata.iata._2015._00._2020_1.iata_servicelistrq.IATAServiceListRQ;
import org.iata.iata._2015._00._2020_1.iata_servicelistrs.IATAServiceListRS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CraneNDCService", targetNamespace = "cranendc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.iata.iata._2015._00._2020_1.iata_airlineprofilerq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_airlineprofilers.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_airshoppingrq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_airshoppingrs.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_offerpricerq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_offerpricers.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderchangerq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_ordercreaterq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderreshoprq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderreshoprs.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderretrieverq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderrulesrq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderrulesrs.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_orderviewrs.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_seatavailabilityrq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_seatavailabilityrs.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_servicelistrq.ObjectFactory.class,
    org.iata.iata._2015._00._2020_1.iata_servicelistrs.ObjectFactory.class
})
public interface CraneNDCService {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_airlineprofilers.IATAAirlineProfileRS
     */
    @WebMethod(action = "cranendc/doAirlineProfile")
    @WebResult(name = "IATA_AirlineProfileRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_AirlineProfileRS", partName = "parameters")
    public IATAAirlineProfileRS doAirlineProfile(
        @WebParam(name = "IATA_AirlineProfileRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_AirlineProfileRQ", partName = "parameters")
        IATAAirlineProfileRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_airlineprofilers.IATAAirlineProfileRS
     */
    @WebMethod(action = "cranendc/doGeneralParams")
    @WebResult(name = "IATA_AirlineProfileRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_AirlineProfileRS", partName = "parameters")
    public IATAAirlineProfileRS doGeneralParams(
        @WebParam(name = "IATA_AirlineProfileRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_AirlineProfileRQ", partName = "parameters")
        IATAAirlineProfileRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_airshoppingrs.IATAAirShoppingRS
     */
    @WebMethod(action = "cranendc/doAirShopping")
    @WebResult(name = "IATA_AirShoppingRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_AirShoppingRS", partName = "parameters")
    public IATAAirShoppingRS doAirShopping(
        @WebParam(name = "IATA_AirShoppingRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_AirShoppingRQ", partName = "parameters")
        IATAAirShoppingRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doOrderCreate")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doOrderCreate(
        @WebParam(name = "IATA_OrderCreateRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderCreateRQ", partName = "parameters")
        IATAOrderCreateRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doOrderChange")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doOrderChange(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doOrderRetrieve")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doOrderRetrieve(
        @WebParam(name = "IATA_OrderRetrieveRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderRetrieveRQ", partName = "parameters")
        IATAOrderRetrieveRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doTicketPreview")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doTicketPreview(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_servicelistrs.IATAServiceListRS
     */
    @WebMethod(action = "cranendc/doServiceList")
    @WebResult(name = "IATA_ServiceListRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_ServiceListRS", partName = "parameters")
    public IATAServiceListRS doServiceList(
        @WebParam(name = "IATA_ServiceListRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_ServiceListRQ", partName = "parameters")
        IATAServiceListRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_servicelistrs.IATAServiceListRS
     */
    @WebMethod(action = "cranendc/doBaggageServiceList")
    @WebResult(name = "IATA_ServiceListRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_ServiceListRS", partName = "parameters")
    public IATAServiceListRS doBaggageServiceList(
        @WebParam(name = "IATA_ServiceListRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_ServiceListRQ", partName = "parameters")
        IATAServiceListRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_seatavailabilityrs.IATASeatAvailabilityRS
     */
    @WebMethod(action = "cranendc/doSeatAvailability")
    @WebResult(name = "IATA_SeatAvailabilityRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_SeatAvailabilityRS", partName = "parameters")
    public IATASeatAvailabilityRS doSeatAvailability(
        @WebParam(name = "IATA_SeatAvailabilityRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_SeatAvailabilityRQ", partName = "parameters")
        IATASeatAvailabilityRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_offerpricers.IATAOfferPriceRS
     */
    @WebMethod(action = "cranendc/doOfferPrice")
    @WebResult(name = "IATA_OfferPriceRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OfferPriceRS", partName = "parameters")
    public IATAOfferPriceRS doOfferPrice(
        @WebParam(name = "IATA_OfferPriceRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OfferPriceRQ", partName = "parameters")
        IATAOfferPriceRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doAddAncillary")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doAddAncillary(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doDeleteAncillary")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doDeleteAncillary(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doSellAncillary")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doSellAncillary(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderreshoprs.IATAOrderReshopRS
     */
    @WebMethod(action = "cranendc/doOrderCancelPreview")
    @WebResult(name = "IATA_OrderReshopRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderReshopRS", partName = "parameters")
    public IATAOrderReshopRS doOrderCancelPreview(
        @WebParam(name = "IATA_OrderReshopRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderReshopRQ", partName = "parameters")
        IATAOrderReshopRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doOrderCancelCommit")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doOrderCancelCommit(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doVoidTicket")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doVoidTicket(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderreshoprs.IATAOrderReshopRS
     */
    @WebMethod(action = "cranendc/doReissuePreview")
    @WebResult(name = "IATA_OrderReshopRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderReshopRS", partName = "parameters")
    public IATAOrderReshopRS doReissuePreview(
        @WebParam(name = "IATA_OrderReshopRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderReshopRQ", partName = "parameters")
        IATAOrderReshopRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doReissueCommit")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doReissueCommit(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doSplit")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doSplit(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderrulesrs.IATAOrderRulesRS
     */
    @WebMethod(action = "cranendc/doOrderFare")
    @WebResult(name = "IATA_OrderRulesRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderRulesRS", partName = "parameters")
    public IATAOrderRulesRS doOrderFare(
        @WebParam(name = "IATA_OrderRulesRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderRulesRQ", partName = "parameters")
        IATAOrderRulesRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata._2015._00._2020_1.iata_orderviewrs.IATAOrderViewRS
     */
    @WebMethod(action = "cranendc/doUpdatePax")
    @WebResult(name = "IATA_OrderViewRS", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderViewRS", partName = "parameters")
    public IATAOrderViewRS doUpdatePax(
        @WebParam(name = "IATA_OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/2015/00/2020.1/IATA_OrderChangeRQ", partName = "parameters")
        IATAOrderChangeRQ parameters);

}
