
package cranendc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CraneNDCServiceImpl", targetNamespace = "cranendc", wsdlLocation = "file:/D:/Projects/ndcclient/CraneNDCService.wsdl")
public class CraneNDCServiceImpl
    extends Service
{

    private final static URL CRANENDCSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException CRANENDCSERVICEIMPL_EXCEPTION;
    private final static QName CRANENDCSERVICEIMPL_QNAME = new QName("cranendc", "CraneNDCServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Projects/ndcclient/CraneNDCService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRANENDCSERVICEIMPL_WSDL_LOCATION = url;
        CRANENDCSERVICEIMPL_EXCEPTION = e;
    }

    public CraneNDCServiceImpl() {
        super(__getWsdlLocation(), CRANENDCSERVICEIMPL_QNAME);
    }

    public CraneNDCServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRANENDCSERVICEIMPL_QNAME, features);
    }

    public CraneNDCServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, CRANENDCSERVICEIMPL_QNAME);
    }

    public CraneNDCServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRANENDCSERVICEIMPL_QNAME, features);
    }

    public CraneNDCServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CraneNDCServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CraneNDCService
     */
    @WebEndpoint(name = "CraneNDCSOAP")
    public CraneNDCService getCraneNDCSOAP() {
        return super.getPort(new QName("cranendc", "CraneNDCSOAP"), CraneNDCService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CraneNDCService
     */
    @WebEndpoint(name = "CraneNDCSOAP")
    public CraneNDCService getCraneNDCSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("cranendc", "CraneNDCSOAP"), CraneNDCService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRANENDCSERVICEIMPL_EXCEPTION!= null) {
            throw CRANENDCSERVICEIMPL_EXCEPTION;
        }
        return CRANENDCSERVICEIMPL_WSDL_LOCATION;
    }

}
